### ISSUE TITLE
make plotapp code run on remote system

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/plotapp#14]
Could we make the plotapp code be deployable to a web server other than the opencpu server?

**Comment by jeroenooms** [comment]
The plotapp already lets you do this [see code here](https://github.com/mobilizingcs/plotapp/blob/master/inst/www/js/app.js#L208-L211). So if you want to host the front-end yourself you can just copy the contents of [inst/www](https://github.com/mobilizingcs/plotapp/tree/master/inst/www) to `/app/plotapp` or whever.

However it is very important that the app front-end code and R code are in sync. Currently you get that for free because they are packaged together. If you are going to manually deploy the app front-end code you must make sure it gets updated each time the package is redeployed.
